# Generated by Django 3.0.6 on 2020-05-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tite',
            new_name='title',
        ),
    ]
