# Generated by Django 3.0.6 on 2020-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
